Download the dataset from [kaggle](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data).

In [42]:
import numpy as np
import pandas as pd
import math

Remove `id` and `Unnamed: 32` columns since they are not useful for training.

In [43]:
dataset_path = "/content/sample_data/data.csv"
dataset_df = pd.read_csv(dataset_path)
dataset_df = dataset_df.drop(columns="id")
dataset_df = dataset_df.drop(columns="Unnamed: 32")
dataset_df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

The `diagnosis` column values are actually the targets, turn them from `strings` into either `1` or `0`.

In [44]:
targets = dataset_df["diagnosis"]
targets = np.array([1 if target == "M" else 0 for target in targets], dtype=np.float64)

Remove the `diagnosis` column from `dataset_df`.

In [45]:
dataset_df = dataset_df.drop(columns="diagnosis")

 Turn `dataset_df` dataframe into `features` numpy array.

In [46]:
features = dataset_df.to_numpy()

After separating features from targets and cleaning the dataset, get the training set dimensions.
- m = number of training examples (rows in numpy array)
- n = features per example (columns in numpy array)

In [47]:
m, n = features.shape

Sigmoid function, also called __logistic function__ or __logit function__, takes any input `z` and maps it to a value `y` between `0` and `1`.

In [48]:
def sigmoid(z):
  return 1/(1+(np.exp(-z)))

Now that we have a way to map a continuos range of numbers to a range of numbers between `0` and `1`, we can apply the sigmoid function to a linear regression.

Remember that the Z fed to the sigmoid function is the result of:
`Z = W . X + b`.

Generate an array of random weights (W), we need a weight for each input (feature), for simplicity initialize them to `0`.

In [49]:
#w_array = np.random.randn(n)
w_array = np.zeros(n)

Generate a random bias (b), for simplicity initialize it to `0`.

In [50]:
# b = np.random.random()
b = 0

Calculate Z.

In [51]:
# z_array = np.array([np.dot(w_array, row) + b for _, row in dataset_df.iterrows()], dtype=np.float64)
z_array = features.dot(w_array) + b
# z_array = [row for _, row in dataset_df.iterrows()]
# z_array.sort()
z_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

Feeding the Z values for each training set into the sigmoid

In [68]:
y_pred = sigmoid(features.dot(w_array) + b)
y_pred

<ipython-input-48-35506de03d56>:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+(np.exp(-z)))


array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 1.12602680e-274, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

Calculate the derivates of the loss function with respect to the weights and bias.

In [66]:
dw = (1/m)*np.dot(features.T,(y_pred - targets))
db = (1/m)*np.sum(y_pred - targets)

Update the weights and biases.

In [67]:
w_array = w_array - 0.01 * dw
b = b - 0.01 * db
w_array, b

(array([-9.29278120e-02, -1.60255975e-01, -5.79896485e-01, -1.79115202e+00,
        -8.75475923e-04, -4.44741828e-04,  1.76097245e-04,  8.83661687e-05,
        -1.65405888e-03, -6.35797540e-04, -1.05193761e-03, -1.23746643e-02,
        -7.21049649e-03,  7.46345343e-02, -7.49784271e-05, -1.55856318e-04,
        -1.74025510e-04, -7.04521090e-05, -2.08450334e-04, -3.43291872e-05,
        -9.17504833e-02, -2.04991388e-01, -5.74640334e-01, -8.17762742e-01,
        -1.15053717e-03, -7.70495343e-04, -8.91844903e-05, -1.49211116e-04,
        -2.43113708e-03, -7.34543497e-04]),
 -0.010096660808435852)

In [41]:
def training_loop(iterations, learning_rate, w, b, features, targets):
  for i in range(iterations):
    y_pred = sigmoid(features.dot(w) + b)
    dw = (1/m)*np.dot(features.T,(y_pred - targets))
    db = (1/m)*np.sum(y_pred - targets)
    w = w - learning_rate * dw
    b = b - learning_rate * db
  return y_pred

training_loop(100, 0.01, w_array, b, features, targets)


<ipython-input-24-35506de03d56>:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+(np.exp(-z)))


array([1.00000000e+000, 6.92453232e-157, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 8.96669042e-236, 4.22836947e-013, 7.17055713e-180,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
       1.00000000e+000, 1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.00000000e+000, 0.00000000e+000, 3.74242715e-011, 1.00000000e+000,
       8.36551470e-243, 1.00000000e+000, 1.65063013e-074, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 6.82707870e-251, 1.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0