#### Iterating the list and the numpy array

In [16]:
import numpy as np

my_list = [1,2,3,4]
my_np_array = np.array([1,2,3,4])

for ele in my_list:
  print(ele, type(ele))

for ele in my_np_array:
  print(ele, type(ele))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>


#### Trying to append to a list will suceed but trying to append to a numpy array will fail because a numpy array is fixed, just enough memory for the needed elements will be allocated

In [17]:
my_list.append(4)
print(my_list)

[1, 2, 3, 4, 4]


In [18]:
#my_np_array.append(4) this line throws an AttributeError 'numpy.ndarray' object has no attribute 'append'

#### Effects of using `+` operator on lists:

In [19]:
#print(my_list + 5) #Throws TypeError 'can only concatenate list (not "int") to l'
print(my_list + [5])#performs the same operation as my_list.append(5)

[1, 2, 3, 4, 4, 5]


#### Effects of using `+` operator on numpy arrays

In [20]:
print(my_np_array + 5) #adds 5 to every element of the numpy array in a single operation
print(my_np_array + [5]) #adds 5 to every element of the numpy array in a single operation
#print(my_np_array + [5,2]) #Throws ValueError 'operands could not be broadcast together with shapes (4,) (2,)', seems you can only broadcast scalars

[6 7 8 9]
[6 7 8 9]


#### What is broadcasting in Numpy??

#### Vector addition in numpy

In [21]:
my_other_np_array = np.array([1,2,3,4])
print(my_other_np_array + my_np_array)#at this point my_np_array == [1,2,3,4]

[2 4 6 8]


#### Effects of using `*` operator on lists

In [22]:
my_list * 2#using '*' operator on lists repeats the list contents

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

#### Effects of using `*` operator on numpy arrays

In [23]:
2 * my_np_array
[2] * my_np_array
#[2,4] * my_np_array#Throws ValueError 'operands could not be broadcast together with shapes (4,) (2,)', seems you can only broadcast scalars

array([2, 4, 6, 8])

#### Most of numpy operations are applied element wise
- np.sqrt() returns the square root of each element in the numpy array
- np.log() returns the logarithm of each element in the numpy array
- np.array() ** n returns the nth power of each element in the numpy array

#### The Dot product

The dot product can be defined algebraically or geometrically

Coordinate definition:

A . B = sum(Ai * Bi i=0->n)

Geometric definition:

An eucledian vector is a geometric object which posseses both magnitude and direction.

The magnitude of an eucledian vector is equal to the square root of the dot product of an eucledian vector with itself

Ø is the angle between A and B

A . B = ||A||.||B||cos Ø

#### Algebraic definition of the dot product

In [24]:
#Dot product done naively with numpy
np.sum(my_np_array * my_other_np_array)#30

#Using built-in dot product class method from numpy
np.dot(my_np_array, my_other_np_array)#30

#most of the class methods from numpy can also be used as instance methods
(my_np_array * my_other_np_array).sum()
my_np_array.dot(my_other_np_array)

30

#### Geometric definition of the dot product

In [25]:
#getting the my_np_array magnitude
np.sqrt(my_np_array.dot(my_np_array))
#getting the my_other_np_array magniture
np.sqrt(np.dot(my_other_np_array, my_other_np_array))

#since this is such an ubiquitous operation numpy counts with the built-in norm method from the linalg module
#getting the my_np_array magnitude
np.linalg.norm(my_np_array)
#getting the my_other_np_array magniture
np.linalg.norm(my_other_np_array)

5.477225575051661

#### Solving linear systems

The admission fee at a small fair is \$1.50 for children and \$4.00 for adults. On a certain day, 2200 people enter the fair, and \$5050 is collected, how many children and adults attended.

In [26]:
A = np.array([[1,1],[1.5,4.0]])
b = np.array([[2200], [5050]])

np.linalg.solve(A, b)

array([[1500.],
       [ 700.]])

#### Generating data

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [29]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Generate random data

In [30]:
np.random.random(2)

array([0.86124769, 0.1242296 ])

In [31]:
np.random.random((2,3))

array([[0.70398214, 0.74156927, 0.42228008],
       [0.42980676, 0.64313432, 0.14735853]])

In [32]:
np.random.randint(-3, 3, (2,2))

array([[-2, -1],
       [ 2,  2]])

#### Implementing matrix multiplication with lists and comparing against numpy matrix multiplication

Consider two input matrixes:
- matrix A of dimensions (m1, n1)
    where
      m1 is the number of rows of matrix A
      n1 is the number of cols of matrix A
    
- matrix B of dimensions (m2, n2)
    where
      m2 is the number of rows of matrix B
      n2 is the number of cols of matrix B

the output matrix will be:
- matrix C of dimension (m1, n2)
    where
      m1 is the number of rows of matrix A
      n2 is the number of cols of matrix B

1. check matrix A number of columns corresponds to matrix B number of rows

2. create zeros matrix with the same number of rows of matrix A and the same number of columns of matrix B


To implement matrix multiplication we need the whole row from the first matrix and the whole column from the second matrix, these need to have the same lenght!

then we iterate over each row and column, multiplying term by term to finally sum all the products

the output cell will be located at the current row from matrix a and the current colum from matrixb

In [33]:
matrix_A = [[1,1,1], [1,1,1]]
matrix_B = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]


matrix_A_rows = len(matrix_A)
matrix_A_cols = len(matrix_A[0])
matrix_B_rows = len(matrix_B)
matrix_B_cols = len(matrix_B[0])

def get_matrix_column(col_i, matrix):
  return [matrix[row_i][col_i] for row_i in range(len(matrix))]


if matrix_A_cols != matrix_B_rows:
  raise "matrix dimensions are not adequate for multiplication"

matrix_c = []
for _ in range(matrix_A_rows):
  matrix_c.append([0 for _ in range(matrix_B_cols)])

print(matrix_c)

for i in range(matrix_A_rows):
  curr_row = matrix_A[i]
  for j in range(matrix_B_cols):
    curr_col = get_matrix_column(j, matrix_B)
    sum = 0
    for k in range(len(curr_row)):
      sum += (curr_row[k]*curr_col[k])
    matrix_c[i][j] = sum

print(matrix_c)

print(get_matrix_column(0, matrix_B))
print(get_matrix_column(1, matrix_B))

print(np.dot(matrix_A, matrix_B))



[[0, 0, 0, 0], [0, 0, 0, 0]]
[[15, 18, 21, 24], [15, 18, 21, 24]]
[1, 5, 9]
[2, 6, 10]
[[15 18 21 24]
 [15 18 21 24]]
